### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/node-module-glpi#14]
Hi, @Gianfranco97 

I will put here all possible errors for the library.

**Comment by ajsb85** [comment]
When the API does not return a JSON code I got a SyntaxError about the Unexpected token.
Instead print a proper error message in JSON file format. 

```console
node example-initSessionByCredentials.js
undefined:1
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at _prepareRequest (/Users/<user>/GitHub/glpi/node-module-glpi/lib/restclient.js:78:31)
    at IncomingMessage.resp.on (/Users/<user>/GitHub/glpi/node-module-glpi/lib/restclient.js:59:5)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
<user>:example <user>$
```

**Comment by Gianfranco97** [comment]
Sure. I'll check that

**Comment by ajsb85** [comment]
In the method killSession, when no session token the promise is rejected with a text message:  "Uninitialized session" (https://git.io/vFv2D) but for resolve you use the format in JSON.

An example for a message in the reject:

```javascript
{
  status: 400,
  data: [
    'ERROR_SESSION_TOKEN_MISSING',
    '....'
  ]
}
```

Reference: https://git.io/vFv2o

**Comment by ajsb85** [comment]
Hi, @Gianfranco97 

Could you split the error message in the semicolon to clean the error message?

Example:

> missing parameter app_token; view documentation in your browser at https://dev.flyve.org/glpi/apirest.php/#ERROR_APP_TOKEN_PARAMETERS_MISSING

Output
> missing parameter app_token

**Comment by ajsb85** [comment]
I think, is better to print only "data"
For "success" and "fails".

**Comment by Gianfranco97** [comment]
This issue is already resolved, it includes handling errors when returning a failed response that should be able to prevent this from happening again.

I already changed the way I handle the errors, I no longer make them an object and I split the error message in the semicolon as I was asked. Thus we see a message of a failed request in the library:

```js
{ 
  status: 401,
  data: [ 
    'ERROR_GLPI_LOGIN', 
    'Incorrect username or password' 
  ]
}
```

I have not withdrawn the status of the object returned since although it is true that users could know if they are in the presence of an error without the presence of these, it is also true that there is always the possibility that to someone this fact is a useful one.
